version: '3'

services:
  redis:
    image: redis
    env_file:
      - ./src/.env_redis
    command: redis-server --requirepass $${REDIS_PASS}
    ports:
      - "6379:6379"
    networks:
        <<>>_net:
            ipv4_address: 10.10.0.4
  web:
    build: ./web
    command: gunicorn django-project-to-copy.wsgi:application --bind 0.0.0.0:8080 --log-level=critical
    volumes:
      - ./src/:/src:rw
    expose:
      - 8080
    depends_on:
      - redis
    networks:
        <<>>_net:
            ipv4_address: 10.10.0.2
    env_file:
      - ./src/.env
networks:
    <<>>_net:
        ipam:
            driver: default
            config:
              - subnet: 10.10.0.0/24
