version: '3'

services:
  db:
    image: postgres
    environment:
        POSTGRES_DB: "djangosys"
        POSTGRES_USER: "django"
        POSTGRES_PASSWORD: "django-project-to-copy"
        TZ: 'GMT'
    volumes:
      - ./database/:/var/lib/postgresql/data:rw
    networks:
        django-project-to-copy_net:
            ipv4_address: 10.10.0.3
  redis:
    image: redis
    env_file:
      - ./src/.env_redis
    command: redis-server --requirepass $${REDIS_PASS}
    ports:
      - "6379:6379"
    networks:
        django-project-to-copy_net:
            ipv4_address: 10.10.0.4
  web:
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - ./src/:/src:rw
    ports:
     - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - ./src/.env
    networks:
        django-project-to-copy_net:
            ipv4_address: 10.10.0.5

networks:
    django-project-to-copy_net:
        ipam:
            driver: default
            config:
              - subnet: 10.10.0.0/24
